DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BRAND_ID VARCHAR(20) NOT NULL,
  START_DATE TIME,
  END_DATE TIME,
  price_list VARCHAR(20) NOT NULL,
  PRODUCT_ID VARCHAR(20) NOT NULL,
  PRIORITY INT DEFAULT 0,
  PRICE DECIMAL(20, 2) NOT NULL,
  CURR VARCHAR(3) NOT NULL
);